version: '3'

services:
  database:
    container_name: SubmitDatabase
    build: database/
    networks:
      - submitnetwork
    ports:
      - '5432:5432'

  express:
    container_name: SubmitExpress
    build: server/
    depends_on:
      - 'database'
    ports:
      - '3000:3000'
    networks:
      - submitnetwork
    volumes:
      - './server:/app'

networks:
  submitnetwork: